language: python
group: travis_latest

git:
  depth: 25
  quiet: true

python:
- 3.7
- 3.6

matrix:
  include:
  - os: linux
    name: Nose Tests
    python: 3.7
    install: pip install -e .[tests,cov]
  - os: osx
    language: minimal
    install: pip3 install -e .[tests]
  - os: windows
    language: minimal
    before_install:
    - choco install python3
    - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"

install: pip install -r requirements.txt

script: python setup.py test